moov-io/api

Dockerfile
openapi.yaml

Fixes: https://github.com/moov-io/api/issues/2

run a linter over our OpenAPI spec file

---

openapi.yaml

Issue: https://github.com/moov-io/auth/pull/17

docs: clarify oauth2 token expires and multiplicity

---

openapi.yaml

Fixes: https://github.com/moov-io/api/issues/10

drop 'expand' query param

---

openapi.yaml

Fields like 'status' and 'created' are created by the server, not clients.

remove extra fields from requestBodies

---

openapi.yaml

fix rendering of user request bodies

---

openapi.yaml

Issue: https://github.com/moov-io/api/issues/17

add Batch endpoints

---

Dockerfile

Issue: https://github.com/moov-io/infra/issues/25

docker: run as moov (unprivileged) user 

---

openapi.yaml

Issue: https://github.com/moov-io/auth/issues/39

add user profile update - PATCH /users/{user_id}

---

openapi.yaml

Issue: https://github.com/moov-io/api/issues/17
Issue: https://github.com/moov-io/api/issues/5

more batch properties

---

internal/version/version.go
makefile
openapi.yaml

https://github.com/OpenAPITools/openapi-generator/issues/1112 looks somewhat related, but I'm really not sure.  Anyway, the Go client is generated now.

Fix openapitools generate

---

cmd/apitest/main.go

This is related to https://github.com/moov-io/api/issues/26, but just a really simple starting point.

cmd/apitest: ping all apps, add x-request-id

---

Dockerfile

See: https://github.com/Rebilly/ReDoc/issues/698#issuecomment-436230806

build: bump redoc-cli to 0.7.0

---

Dockerfile

Issue: https://github.com/moov-io/infra/issues/35

build: upgrade nginx to 1.15.6

---

openapi.yaml

Issue: https://github.com/moov-io/api/issues/17

api: fix File request json, AddBatch accepts a full Batch object

---

openapi.yaml

Issue: https://github.com/moov-io/auth/issues/53

api: add X-Idempotency-Key on every post and patch

---

openapi.yaml

Issue: https://github.com/moov-io/paygate/issues/22

api: split microdeposit actions into "initiate" and "validate" endpoints

---

openapi.yaml

Issue: https://github.com/moov-io/ach/issues/380

docs: add signup flow, Transfer create and File validate/tabulate steps

---

openapi.yaml

Issue: https://github.com/moov-io/go-client/issues/4

api: fix NPE errors from OpenAPITools

---

.travis.yml
cmd/apitest/main.go
cmd/apitest/signup.go
cmd/apitest/signup_test.go
cmd/apitest/transport_test.go
go.mod
go.sum
vendor/github.com/docker/docker/AUTHORS
vendor/github.com/docker/docker/LICENSE
vendor/github.com/docker/docker/NOTICE
vendor/github.com/docker/docker/pkg/namesgenerator/names-generator.go
vendor/github.com/docker/docker/pkg/random/random.go
vendor/github.com/moov-io/go-client/client/README.md
vendor/github.com/moov-io/go-client/client/api_user.go
vendor/github.com/moov-io/go-client/client/model_create_user.go
vendor/modules.txt

Issue: https://github.com/moov-io/api/issues/26

cmd/apitest: create user against Moov API

---

.travis.yml

Issue: https://github.com/moov-io/api/issues/26

build: run moov/apitest:latest in CI

---

cmd/apitest/login.go
cmd/apitest/main.go
cmd/apitest/signup.go
cmd/apitest/signup_test.go

Issue: https://github.com/moov-io/api/issues/46

cmd/apitest: use the cookie from signup to verify we're logged-in

---

cmd/apitest/login.go
cmd/apitest/main.go
cmd/apitest/signup.go
cmd/apitest/transport.go

Fixes: https://github.com/moov-io/api/issues/49

cmd/apitest: Login Failure, support -local for paygate

---

openapi.yaml

Issue: https://github.com/moov-io/base/issues/7

api: switch timestamps to ISO 8601

---

openapi.yaml

See: https://github.com/moov-io/ach/pull/443

api: revert back to YYMMDD / HHMM for ACH date/time

---

openapi.yaml

Issue: https://github.com/moov-io/ofac/issues/19

api: add OFAC endpoints

---

README.md
cmd/apitest/local/transport.go
cmd/apitest/main.go
cmd/localdevproxy/main.go
makefile
vendor/github.com/moov-io/base/k8s/kubernetes.go
vendor/modules.txt

Issue: https://github.com/moov-io/infra/issues/34

cmd: setup localdevproxy to run in Kubernetes clusters (for local dev)

---

openapi.yaml

Issue: https://github.com/moov-io/gl/issues/6

api: add GL endpoints

---

Dockerfile
Dockerfile-apitest
Dockerfile-localdevproxy

See: https://golang.org/doc/go1.13

build: upgrade to Go 1.13 and Node.js 12

---

apps/accounts/index.html
apps/ach/index.html
apps/auth/index.html
apps/customers/index.html
apps/fed/index.html
apps/imagecashletter/index.html
apps/paygate/index.html
apps/scroll.js
apps/watchman/index.html
apps/wire/index.html

See: https://mrin9.github.io/RapiDoc/api.html

apps: support URL fragments for scrolling

---

site/admin/customers/index.html
site/admin/index.html
site/admin/watchman/index.html

Fixes: https://github.com/moov-io/api/issues/137

site/admin: include Customers and Watchman admin endpoint docs

---

.dockerignore
.gitignore
cmd/writeVersions/main.go
go.sum
makefile
openapi.yaml.tpl
site/admin/customers/index.html.tpl
site/admin/paygate/index.html.tpl
site/admin/watchman/index.html.tpl
site/apps/accounts/index.html.tpl
site/apps/ach/index.html.tpl
site/apps/auth/index.html.tpl
site/apps/customers/index.html.tpl
site/apps/fed/index.html.tpl
site/apps/imagecashletter/index.html.tpl
site/apps/paygate/index.html.tpl
site/apps/watchman/index.html.tpl
site/apps/wire/index.html.tpl

Issue: https://github.com/moov-io/api/issues/140

site: use templates to include versioned OpenAPI dependency specifications

---

cmd/apitest/accounts.go
cmd/apitest/gateway.go
cmd/apitest/local/transport.go
cmd/apitest/main.go

Needed as part of https://github.com/moov-io/paygate/pull/463

cmd/apitest: setup the Gateway before transfers

---

openapi.yaml

Removed broken links to example files

Removing broken links
